# Generated by Django 5.2.3 on 2025-06-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_telegrammessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
